import { AppShell } from '@/components/AppShell';
import { AuthGate } from '@/components/AuthGate';
import { PageHeader } from '@/components/Page';
import { prisma } from '@/lib/prisma';
import { compareAllocationKeys } from '@/lib/allocation';

export default async function Page({searchParams}:{searchParams:Promise<{key?:string;a?:string;b?:string;asOf?:string}>}){
  const s=await AuthGate(); const q=await searchParams; const asOf=new Date(q.asOf||Date.now());
  const [keys,dcs,modes,lanes,carriers]=await Promise.all([
    prisma.allocationKey.findMany({where:{tenantId:s.tenantId},include:{dc:true,mode:true,_count:{select:{rules:true}}},orderBy:[{createdAt:'desc'}]}),
    prisma.distributionCentre.findMany({where:{tenantId:s.tenantId,active:true},orderBy:{code:'asc'}}),
    prisma.transportMode.findMany({where:{tenantId:s.tenantId,active:true},orderBy:{code:'asc'}}),
    prisma.lane.findMany({where:{tenantId:s.tenantId,active:true},include:{dc:true,mode:true},orderBy:{destinationCountry:'asc'}}),
    prisma.carrier.findMany({where:{tenantId:s.tenantId,active:true},orderBy:{name:'asc'}})
  ]);
  const chosenId=q.key??keys.find(k=>k.status==='DRAFT')?.id??keys.find(k=>k.status==='ACTIVE')?.id;
  const chosen=chosenId?await prisma.allocationKey.findFirst({where:{id:chosenId,tenantId:s.tenantId},include:{dc:true,mode:true,rules:{include:{carrier:true,lane:true},orderBy:[{laneId:'asc'},{position:'asc'}]}}}):null;
  const comparison=q.a&&q.b?await compareAllocationKeys(s.tenantId,q.a,q.b,asOf).catch(()=>null):null;
  const activeKeys=keys.filter(k=>k.status==='ACTIVE').length,draftKeys=keys.filter(k=>k.status==='DRAFT').length,expiredKeys=keys.filter(k=>k.status==='EXPIRED').length,totalRules=keys.reduce((sum,k)=>sum+k._count.rules,0);
  return <AppShell><PageHeader eyebrow="Versioned allocation keys" title="Allocations" description="Govern carrier ladders by lane, maintain Draft-to-Publish control and compare allocation changes before they become operational." actions={<><a className="btn" href="/imports">Import key</a>{chosen&&<a className="btn" href={'/api/export/allocations?keyId='+chosen.id}>Export key</a>}</>}/>
    <div className="summaryStrip"><div className="summaryCell"><div className="summaryLabel">Active keys</div><div className="summaryValue">{activeKeys}</div><div className="summaryNote">Published operational scopes</div></div><div className="summaryCell"><div className="summaryLabel">Draft keys</div><div className="summaryValue">{draftKeys}</div><div className="summaryNote">Awaiting review / publish</div></div><div className="summaryCell"><div className="summaryLabel">Historical keys</div><div className="summaryValue">{expiredKeys}</div><div className="summaryNote">Expired controlled versions</div></div><div className="summaryCell"><div className="summaryLabel">Allocation rules</div><div className="summaryValue">{totalRules.toLocaleString()}</div><div className="summaryNote">Primary through Backup 2</div></div></div>
    <div className="two"><div className="card"><h2>Create Draft from Active</h2><form action="/api/allocations/draft" method="post" className="stack"><input type="hidden" name="action" value="create"/><div className="field"><label>DC</label><select name="dcId" required><option value="">Select</option>{dcs.map(d=><option key={d.id} value={d.id}>{d.code}</option>)}</select></div><div className="field"><label>Mode</label><select name="modeId" required><option value="">Select</option>{modes.map(m=><option key={m.id} value={m.id}>{m.code}</option>)}</select></div><div className="field"><label>Change note</label><input name="changeNote"/></div><button className="btn primary">Create / open Draft</button></form></div>
      <div className="card"><h2>Key versions</h2><div className="stack">{keys.slice(0,20).map(k=><a key={k.id} className="btn" href={'/allocations?key='+k.id}>{k.displayKey} · {k.status} · {k._count.rules} rules</a>)}</div></div></div>
    {chosen&&<><div className="section card"><h2>{chosen.displayKey} · {chosen.status}</h2><p className="muted">{chosen.dc?.code??'All DCs'} / {chosen.mode?.code??'All modes'} · v{chosen.version} · source {chosen.source}</p>
      {chosen.status==='DRAFT'&&<form action="/api/allocations/publish" method="post" className="toolbar"><input type="hidden" name="keyId" value={chosen.id}/><button className="btn gold">Publish Draft</button></form>}
    </div><div className="section tableWrap"><table className="table"><thead><tr><th>Lane</th><th>Customer</th><th>ZIP</th><th>Position</th><th>Carrier</th><th>%</th><th>Notes</th></tr></thead><tbody>{chosen.rules.map(r=><tr key={r.id}><td>{r.lane.laneIdentifier??r.lane.destinationCountry+'-'+r.lane.destinationRegion}</td><td>{r.customerCode??'General'}</td><td>{r.destinationZip??'General'}</td><td>{r.position}</td><td>{r.carrier.name}</td><td>{r.percentage==null?'—':Number(r.percentage).toFixed(1)}</td><td>{r.notes??''}</td></tr>)}</tbody></table></div>
      {chosen.status==='DRAFT'&&<div className="section card"><h2>Add / replace Draft rule</h2><form action="/api/allocations/draft" method="post" className="formgrid"><input type="hidden" name="action" value="saveRule"/><input type="hidden" name="keyId" value={chosen.id}/><div className="field"><label>Lane</label><select name="laneId" required>{lanes.filter(l=>(!chosen.dcId||l.dcId===chosen.dcId)&&(!chosen.modeId||l.modeId===chosen.modeId)).map(l=><option key={l.id} value={l.id}>{l.dc.code} / {l.mode.code} / {l.destinationCountry}-{l.destinationRegion}</option>)}</select></div><div className="field"><label>Position</label><select name="position"><option>PRIMARY</option><option>SECONDARY</option><option>TERTIARY</option><option>BACKUP_1</option><option>BACKUP_2</option></select></div><div className="field"><label>Carrier</label><select name="carrierId" required>{carriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Allocation %</label><input type="number" step="0.01" name="percentage"/></div><div className="field"><label>Customer code (optional)</label><input name="customerCode"/></div><div className="field"><label>Destination ZIP/prefix (optional)</label><input name="destinationZip"/></div><div className="field"><label>Notes</label><input name="notes"/></div><div style={{alignSelf:'end'}}><button className="btn primary">Save Draft rule</button></div></form></div>}
    </>}
    <div className="section card"><h2>Key-to-key comparison</h2><form method="get" className="formgrid"><div className="field"><label>From</label><select name="a" required defaultValue={q.a??''}><option value="">Select</option>{keys.map(k=><option key={k.id} value={k.id}>{k.displayKey}</option>)}</select></div><div className="field"><label>To</label><select name="b" required defaultValue={q.b??''}><option value="">Select</option>{keys.map(k=><option key={k.id} value={k.id}>{k.displayKey}</option>)}</select></div><div className="field"><label>Costing date</label><input type="date" name="asOf" defaultValue={asOf.toISOString().slice(0,10)}/></div><div style={{alignSelf:'end'}}><button className="btn primary">Compare</button></div></form>
      {comparison&&<><div className="notice section">Modelled cost impact: €{comparison.costImpact.from.toFixed(2)} → €{comparison.costImpact.to.toFixed(2)} ({comparison.costImpact.change>=0?'+':''}€{comparison.costImpact.change.toFixed(2)})</div><div className="toolbar section"><a className="btn" href={'/api/export/allocation-comparison?a='+q.a+'&b='+q.b+'&asOf='+asOf.toISOString().slice(0,10)}>Export comparison</a></div><div className="tableWrap section"><table className="table"><thead><tr><th>Change</th><th>Lane</th><th>Position</th><th>From</th><th>To</th><th>Customer</th><th>ZIP</th></tr></thead><tbody>{comparison.changes.map((r:any,i:number)=><tr key={i}><td>{r.change}</td><td>{r.lane}</td><td>{r.position??(r.fromPosition+' → '+r.toPosition)}</td><td>{r.fromCarrier??r.carrier??'—'}</td><td>{r.toCarrier??r.carrier??'—'}</td><td>{r.customerCode??'General'}</td><td>{r.destinationZip??'General'}</td></tr>)}</tbody></table></div></>}
    </div>
  </AppShell>;
}
