import { AppShell } from '@/components/AppShell';
import { AuthGate } from '@/components/AuthGate';
import { PageHeader } from '@/components/Page';
import { prisma } from '@/lib/prisma';

export default async function Page(){
  const s=await AuthGate(); const now=new Date();
  const [carriers,dcs,modes,types,fuel,accessorials]=await Promise.all([
    prisma.carrier.findMany({where:{tenantId:s.tenantId,active:true},orderBy:{name:'asc'}}),
    prisma.distributionCentre.findMany({where:{tenantId:s.tenantId,active:true},orderBy:{code:'asc'}}),
    prisma.transportMode.findMany({where:{tenantId:s.tenantId,active:true},orderBy:{code:'asc'}}),
    prisma.accessorialType.findMany({where:{tenantId:s.tenantId,active:true},orderBy:{code:'asc'}}),
    prisma.fuelSurcharge.findMany({where:{tenantId:s.tenantId},include:{carrier:true,dc:true,mode:true},orderBy:{validFrom:'desc'},take:100}),
    prisma.carrierAccessorial.findMany({where:{tenantId:s.tenantId},include:{carrier:true,type:true,dc:true,mode:true},orderBy:{validFrom:'desc'},take:100})
  ]);
  return <AppShell><PageHeader eyebrow="Separate commercial components" title="Fuel & Accessorials" description="Maintain effective-dated fuel surcharges and accessorial agreements separately from base rates for transparent total-cost modelling."/>
    <div className="summaryStrip"><div className="summaryCell"><div className="summaryLabel">Active carriers</div><div className="summaryValue">{carriers.length}</div><div className="summaryNote">Available commercial counterparts</div></div><div className="summaryCell"><div className="summaryLabel">Fuel versions</div><div className="summaryValue">{fuel.length}</div><div className="summaryNote">Loaded effective-dated records</div></div><div className="summaryCell"><div className="summaryLabel">Accessorial versions</div><div className="summaryValue">{accessorials.length}</div><div className="summaryNote">Carrier charge agreements</div></div><div className="summaryCell"><div className="summaryLabel">Charge types</div><div className="summaryValue">{types.length}</div><div className="summaryNote">Governed accessorial catalogue</div></div></div>
    <div className="two"><div className="card"><h2>Add fuel surcharge version</h2><form action="/api/commercials/fuel" method="post" className="stack"><div className="field"><label>Carrier</label><select name="carrierId" required>{carriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>DC scope (optional)</label><select name="dcId"><option value="">All</option>{dcs.map(d=><option key={d.id} value={d.id}>{d.code}</option>)}</select></div><div className="field"><label>Mode scope (optional)</label><select name="modeId"><option value="">All</option>{modes.map(m=><option key={m.id} value={m.id}>{m.code}</option>)}</select></div><div className="field"><label>Fuel %</label><input name="percentage" type="number" step="0.0001" required/></div><div className="field"><label>Valid from</label><input name="validFrom" type="date" required defaultValue={now.toISOString().slice(0,10)}/></div><div className="field"><label>Valid to</label><input name="validTo" type="date" required/></div><button className="btn primary">Add version</button></form></div>
      <div className="card"><h2>Add accessorial type</h2><form action="/api/commercials/accessorials" method="post" className="stack"><input type="hidden" name="action" value="type"/><div className="field"><label>Code</label><input name="code" required/></div><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Default basis</label><select name="defaultBasis"><option>PER_SHIPMENT</option><option>PER_PALLET</option><option>PER_HOUR</option><option>FLAT</option><option>PERCENT_BASE</option></select></div><div className="field"><label>Description</label><input name="description"/></div><button className="btn primary">Create type</button></form></div></div>
    <div className="section card"><h2>Add carrier accessorial agreement version</h2><form action="/api/commercials/accessorials" method="post" className="formgrid"><input type="hidden" name="action" value="agreement"/><div className="field"><label>Carrier</label><select name="carrierId" required>{carriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Type</label><select name="typeId" required>{types.map(t=><option key={t.id} value={t.id}>{t.code} — {t.name}</option>)}</select></div><div className="field"><label>Amount (EUR / %)</label><input name="amount" type="number" step="0.0001" required/></div><div className="field"><label>Charging basis</label><select name="chargingBasis"><option>PER_SHIPMENT</option><option>PER_PALLET</option><option>PER_HOUR</option><option>FLAT</option><option>PERCENT_BASE</option></select></div><div className="field"><label>DC scope</label><select name="dcId"><option value="">All</option>{dcs.map(d=><option key={d.id} value={d.id}>{d.code}</option>)}</select></div><div className="field"><label>Mode scope</label><select name="modeId"><option value="">All</option>{modes.map(m=><option key={m.id} value={m.id}>{m.code}</option>)}</select></div><div className="field"><label>Destination country</label><input name="destinationCountry"/></div><div className="field"><label>Valid from</label><input name="validFrom" type="date" required/></div><div className="field"><label>Valid to</label><input name="validTo" type="date" required/></div><div style={{alignSelf:'end'}}><button className="btn primary">Add agreement version</button></div></form></div>
    <div className="section two"><div className="card"><h2>Fuel history</h2><div className="tableWrap"><table className="table"><thead><tr><th>Carrier</th><th>Scope</th><th>%</th><th>From</th><th>To</th><th>v</th></tr></thead><tbody>{fuel.map(r=><tr key={r.id}><td>{r.carrier.name}</td><td>{r.dc?.code??'All'} / {r.mode?.code??'All'}</td><td>{Number(r.percentage)}%</td><td>{r.validFrom.toISOString().slice(0,10)}</td><td>{r.validTo.toISOString().slice(0,10)}</td><td>{r.version}</td></tr>)}</tbody></table></div></div><div className="card"><h2>Accessorial history</h2><div className="tableWrap"><table className="table"><thead><tr><th>Type</th><th>Carrier</th><th>Basis</th><th>EUR</th><th>Scope</th><th>v</th></tr></thead><tbody>{accessorials.map(r=><tr key={r.id}><td>{r.type.code}</td><td>{r.carrier.name}</td><td>{r.chargingBasis}</td><td>{Number(r.amount)}</td><td>{r.dc?.code??'All'} / {r.mode?.code??'All'}</td><td>{r.version}</td></tr>)}</tbody></table></div></div></div>
  </AppShell>;
}
