import { AppShell } from '@/components/AppShell';
import { AuthGate } from '@/components/AuthGate';
import { PageHeader } from '@/components/Page';
import { prisma } from '@/lib/prisma';
import { compareRateCards } from '@/lib/rate-analysis';

export default async function Page({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
  const session=await AuthGate(); const q=await searchParams;
  const cards=await prisma.rateCard.findMany({where:{tenantId:session.tenantId},include:{carrier:true,dc:true,mode:true,_count:{select:{rates:true}}},orderBy:[{carrierId:'asc'},{version:'desc'}]});
  const comparison=q.from&&q.to?await compareRateCards({tenantId:session.tenantId,fromId:q.from,toId:q.to}).catch(()=>null):null;
  const now=new Date(); const horizon=new Date(now); horizon.setUTCDate(horizon.getUTCDate()+90);
  const active=cards.filter(c=>c.commercialStatus==='CONTRACTED_ACTIVE'&&c.validFrom<=now&&c.validTo>=now&&c.status!=='SUPERSEDED').length;
  const expiring=cards.filter(c=>c.commercialStatus==='CONTRACTED_ACTIVE'&&c.validTo>=now&&c.validTo<=horizon).length;
  const research=cards.filter(c=>c.commercialStatus==='SUBMISSION_RESEARCH').length;
  const laneRows=cards.reduce((sum,c)=>sum+c._count.rates,0);
  return <AppShell><PageHeader eyebrow="Commercial history" title="Rate Cards" description="Review every commercial rate version, contract validity window and lane-level tariff before modelling network cost." actions={<><a className="btn gold" href="/imports">Upload rate card</a><a className="btn" href="/api/export/rate-cards">Export .xlsx</a></>}/>
    <div className="summaryStrip"><div className="summaryCell"><div className="summaryLabel">Active contracted</div><div className="summaryValue">{active}</div><div className="summaryNote">Valid on the current date</div></div><div className="summaryCell"><div className="summaryLabel">Expiring ≤ 90 days</div><div className="summaryValue">{expiring}</div><div className="summaryNote">Commercial review required</div></div><div className="summaryCell"><div className="summaryLabel">Research submissions</div><div className="summaryValue">{research}</div><div className="summaryNote">Excluded from operational default</div></div><div className="summaryCell"><div className="summaryLabel">Lane-rate rows</div><div className="summaryValue">{laneRows.toLocaleString()}</div><div className="summaryNote">Across all card versions</div></div></div>
    <div className="tableWrap"><table className="table"><thead><tr><th>Carrier</th><th>DC</th><th>Mode</th><th>Valid from</th><th>Valid to</th><th>Commercial</th><th>Status</th><th>Version</th><th>Lanes</th><th>File</th></tr></thead><tbody>{cards.map(c=><tr key={c.id}><td>{c.carrier.name}</td><td>{c.dc.code}</td><td>{c.mode.code}</td><td>{c.validFrom.toISOString().slice(0,10)}</td><td>{c.validTo.toISOString().slice(0,10)}</td><td>{c.commercialStatus}</td><td><span className={c.status==='ACTIVE'?'badge ok':c.status==='FUTURE'?'badge warn':'badge'}>{c.status}</span></td><td>v{c.version}</td><td>{c._count.rates}</td><td>{c.originalFilename}</td></tr>)}</tbody></table></div>
    <div className="section card"><h2>Rate change analysis</h2><form method="get" className="formgrid"><div className="field"><label>Prior / comparison card</label><select name="from" required defaultValue={q.from??''}><option value="">Select</option>{cards.map(c=><option key={c.id} value={c.id}>{c.carrier.code} · {c.dc.code} · {c.mode.code} · v{c.version}</option>)}</select></div><div className="field"><label>New / target card</label><select name="to" required defaultValue={q.to??''}><option value="">Select</option>{cards.map(c=><option key={c.id} value={c.id}>{c.carrier.code} · {c.dc.code} · {c.mode.code} · v{c.version}</option>)}</select></div><div style={{alignSelf:'end'}}><button className="btn primary">Compare</button></div></form>
      {comparison&&<><div className="grid section"><div className="card"><b>Prior annual cost</b><div className="kpi">€{comparison.summary.oldAnnualCost.toLocaleString(undefined,{maximumFractionDigits:0})}</div></div><div className="card"><b>New annual cost</b><div className="kpi">€{comparison.summary.newAnnualCost.toLocaleString(undefined,{maximumFractionDigits:0})}</div></div><div className="card"><b>Annual impact</b><div className="kpi">€{comparison.summary.annualImpact.toLocaleString(undefined,{maximumFractionDigits:0})}</div></div><div className="card"><b>Weighted change</b><div className="kpi">{comparison.summary.weightedPct==null?'—':comparison.summary.weightedPct.toFixed(1)+'%'}</div></div></div><div className="toolbar section"><a className="btn" href={'/api/export/rate-change?from='+q.from+'&to='+q.to}>Export comparison</a></div><div className="tableWrap section"><table className="table"><thead><tr><th>Lane</th><th>Band</th><th>Status</th><th>Prior rate</th><th>New rate</th><th>Change</th><th>%</th><th>Annual impact</th></tr></thead><tbody>{comparison.rows.slice(0,300).map((r:any,i:number)=><tr key={i}><td>{r.lane}</td><td>{r.band??'FTL'}</td><td>{r.status}</td><td>{r.oldRate??'—'}</td><td>{r.newRate??'—'}</td><td>{r.change??'—'}</td><td>{r.changePct==null?'—':r.changePct.toFixed(1)+'%'}</td><td>{r.annualImpact.toFixed(2)}</td></tr>)}</tbody></table></div></>}
    </div>
  </AppShell>;
}
