import { AppShell } from '@/components/AppShell';
import { AuthGate } from '@/components/AuthGate';
import { PageHeader, Kpi } from '@/components/Page';
import { prisma } from '@/lib/prisma';
import { runScenario } from '@/lib/scenario';

export default async function Page({searchParams}:{searchParams:Promise<{id?:string}>}){
  const s=await AuthGate(); const q=await searchParams;
  const [scenarios,lanes,carriers]=await Promise.all([
    prisma.scenario.findMany({where:{tenantId:s.tenantId},include:{_count:{select:{rules:true}}},orderBy:{createdAt:'desc'}}),
    prisma.lane.findMany({where:{tenantId:s.tenantId,active:true},include:{dc:true,mode:true},orderBy:{destinationCountry:'asc'}}),
    prisma.carrier.findMany({where:{tenantId:s.tenantId,active:true},orderBy:{name:'asc'}})
  ]);
  const selectedId=q.id??scenarios[0]?.id; const selected=selectedId?await prisma.scenario.findFirst({where:{id:selectedId,tenantId:s.tenantId},include:{rules:{include:{lane:true,carrier:true,replacementCarrier:true}},promotedAllocationKey:true}}):null;
  const result=selected?await runScenario({tenantId:s.tenantId,scenarioId:selected.id}).catch(()=>null):null;
  return <AppShell><PageHeader eyebrow="Rule-based modelling" title="Scenarios" actions={selected?<a className="btn" href={'/api/export/scenarios?id='+selected.id}>Export scenario</a>:undefined}/>
    <div className="two"><div className="card"><h2>New scenario</h2><form action="/api/scenarios" method="post" className="stack"><input type="hidden" name="action" value="create"/><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Description</label><input name="description"/></div><div className="field"><label>Modelling date</label><input name="modellingDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="field"><label><input type="checkbox" name="enablePalletToFtl"/> Cost eligible pallet shipments at lower of pallet / FTL</label></div><div className="field"><label>Max pallets per FTL</label><input name="maxPalletsPerFtl" type="number" defaultValue={33}/></div><button className="btn primary">Create scenario</button></form></div>
      <div className="card"><h2>Saved scenarios</h2><div className="stack">{scenarios.map(x=><a className="btn" key={x.id} href={'/scenarios?id='+x.id}>{x.name} · {x._count.rules} rules</a>)}</div></div></div>
    {selected&&<><div className="section card"><h2>{selected.name}</h2><p className="muted">{selected.description??'No description'} · modelling {selected.modellingDate.toISOString().slice(0,10)} · FTL conversion {selected.enablePalletToFtl?'enabled':'disabled'}</p>{selected.promotedAllocationKey&&<div className="notice">Promoted to Draft {selected.promotedAllocationKey.displayKey}</div>}</div>
      <div className="section card"><h2>Add scenario rule</h2><form action="/api/scenarios" method="post" className="formgrid"><input type="hidden" name="action" value="rule"/><input type="hidden" name="scenarioId" value={selected.id}/><div className="field"><label>Rule type</label><select name="type"><option>CARRIER_REPLACEMENT</option><option>LANE_SPLIT</option><option>CUSTOMER_ASSIGNMENT</option><option>CUSTOMER_SPLIT</option></select></div><div className="field"><label>Lane</label><select name="laneId" required>{lanes.map(l=><option key={l.id} value={l.id}>{l.dc.code} / {l.mode.code} / {l.destinationCountry}-{l.destinationRegion}</option>)}</select></div><div className="field"><label>Current/source carrier (replacement only)</label><select name="carrierId"><option value="">Any / not applicable</option>{carriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Target carrier</label><select name="replacementCarrierId"><option value="">Not applicable</option>{carriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Customer code</label><input name="customerCode"/></div><div className="field"><label>Split %</label><input type="number" step="0.01" name="percentage"/></div><div className="field"><label>Notes</label><input name="notes"/></div><div style={{alignSelf:'end'}}><button className="btn primary">Add rule</button></div></form></div>
      <div className="section tableWrap"><table className="table"><thead><tr><th>Type</th><th>Lane</th><th>Customer</th><th>Source</th><th>Target</th><th>%</th></tr></thead><tbody>{selected.rules.map(r=><tr key={r.id}><td>{r.type}</td><td>{r.lane.laneIdentifier??r.lane.destinationCountry+'-'+r.lane.destinationRegion}</td><td>{r.customerCode??'General'}</td><td>{r.carrier?.name??'—'}</td><td>{r.replacementCarrier?.name??r.carrier?.name??'—'}</td><td>{r.percentage==null?'—':Number(r.percentage)}</td></tr>)}</tbody></table></div>
      {result&&<div className="grid section"><Kpi label="Baseline cost" value={'€'+result.summary.baselineCost.toLocaleString(undefined,{maximumFractionDigits:0})}/><Kpi label="Scenario cost" value={'€'+result.summary.scenarioCost.toLocaleString(undefined,{maximumFractionDigits:0})}/><Kpi label="Change" value={'€'+result.summary.change.toLocaleString(undefined,{maximumFractionDigits:0})} detail={result.summary.changePct==null?'':result.summary.changePct.toFixed(1)+'%'}/><Kpi label="Converted to FTL" value={result.summary.convertedShipments.toFixed(0)+' shipments'} detail={result.summary.convertedPallets.toFixed(0)+' pallets'}/></div>}
      <div className="section card"><h2>Promote allocation rules to Draft</h2><p className="muted">Pallet-to-FTL conversion is deliberately not promoted. Promotion does not publish.</p><form action="/api/scenarios" method="post" className="toolbar"><input type="hidden" name="action" value="promote"/><input type="hidden" name="scenarioId" value={selected.id}/><input type="hidden" name="merge" value="true"/><button className="btn gold">Promote / merge into Draft</button></form></div>
    </>}
  </AppShell>;
}
