import { AppShell } from '@/components/AppShell';
import { AuthGate } from '@/components/AuthGate';
import { PageHeader } from '@/components/Page';
import { prisma } from '@/lib/prisma';
import { laneAlternatives, palletBreakEven } from '@/lib/cost-engine';

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const session=await AuthGate(); const q=await searchParams; const asOf=new Date(q.asOf||Date.now());
  const [dcs,modes,carriers]=await Promise.all([
    prisma.distributionCentre.findMany({where:{tenantId:session.tenantId,active:true},orderBy:{code:'asc'}}),
    prisma.transportMode.findMany({where:{tenantId:session.tenantId,active:true},orderBy:{code:'asc'}}),
    prisma.carrier.findMany({where:{tenantId:session.tenantId,active:true},orderBy:{name:'asc'}})
  ]);
  const rows=await laneAlternatives({tenantId:session.tenantId,asOf,dcId:q.dcId||undefined,modeId:q.modeId||undefined,destinationCountry:q.country?.toUpperCase()||undefined,destinationRegion:q.region||undefined,carrierId:q.carrierId||undefined,includeResearch:q.research==='1',customerCode:q.customerCode||undefined});
  const cheapest=new Map<string,number>(); for(const r of rows.filter((x:any)=>x.commercialStatus==='CONTRACTED_ACTIVE')){const k=r.lane.id;cheapest.set(k,Math.min(cheapest.get(k)??Infinity,r.total));}
  const enriched=[] as any[]; for(const r of rows.slice(0,200)){const be=await palletBreakEven({tenantId:session.tenantId,laneId:r.lane.id,carrierId:r.carrier.id,asOf});enriched.push({...r,breakEven:be?.breakEven??null});}
  const qs=new URLSearchParams(Object.entries(q).filter(([,v])=>v!=null) as [string,string][]).toString();
  const laneCount=new Set(rows.map((r:any)=>r.lane.id)).size,carrierCount=new Set(rows.map((r:any)=>r.carrier.id)).size,missingCount=rows.filter((r:any)=>r.missing?.length).length;
  const totals=rows.map((r:any)=>Number(r.total)).filter(Number.isFinite); const minCost=totals.length?Math.min(...totals):0,maxCost=totals.length?Math.max(...totals):0;
  return <AppShell><PageHeader eyebrow="Operational alternatives" title="Lane Search & Comparison" description="Search contracted carrier alternatives by lane and compare allocation position, base rate, fuel, accessorials and pallet-to-FTL break-even." actions={<a className="btn" href={'/api/export/lanes?'+qs}>Export results</a>}/>
    <div className="summaryStrip"><div className="summaryCell"><div className="summaryLabel">Matched lanes</div><div className="summaryValue">{laneCount}</div><div className="summaryNote">Current filtered network</div></div><div className="summaryCell"><div className="summaryLabel">Carrier alternatives</div><div className="summaryValue">{carrierCount}</div><div className="summaryNote">Distinct carriers returned</div></div><div className="summaryCell"><div className="summaryLabel">Modelled cost range</div><div className="summaryValue">€{minCost.toLocaleString(undefined,{maximumFractionDigits:0})}</div><div className="summaryNote">to €{maxCost.toLocaleString(undefined,{maximumFractionDigits:0})}</div></div><div className="summaryCell"><div className="summaryLabel">Rows with exceptions</div><div className="summaryValue">{missingCount}</div><div className="summaryNote">Missing commercial components</div></div></div>
    <form method="get" className="card formgrid"><div className="field"><label>DC</label><select name="dcId" defaultValue={q.dcId??''}><option value="">All</option>{dcs.map(d=><option key={d.id} value={d.id}>{d.code}</option>)}</select></div><div className="field"><label>Mode</label><select name="modeId" defaultValue={q.modeId??''}><option value="">All</option>{modes.map(m=><option key={m.id} value={m.id}>{m.code}</option>)}</select></div><div className="field"><label>Destination country</label><input name="country" defaultValue={q.country??''} placeholder="DE"/></div><div className="field"><label>Destination region</label><input name="region" defaultValue={q.region??''} placeholder="06"/></div><div className="field"><label>Carrier</label><select name="carrierId" defaultValue={q.carrierId??''}><option value="">All</option>{carriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Customer code</label><input name="customerCode" defaultValue={q.customerCode??''}/></div><div className="field"><label>Validity date</label><input type="date" name="asOf" defaultValue={asOf.toISOString().slice(0,10)}/></div><div className="field"><label><input type="checkbox" name="research" value="1" defaultChecked={q.research==='1'}/> Include research/historical submissions</label></div><div style={{alignSelf:'end'}}><button className="btn primary">Search</button></div></form>
    <div className="section tableWrap"><table className="table"><thead><tr><th>DC</th><th>Mode</th><th>Lane</th><th>Allocation</th><th>Carrier</th><th>Commercial</th><th>Base</th><th>Fuel</th><th>Accessorials</th><th>Total modelled</th><th>vs cheapest contracted</th><th>FTL break-even</th><th>Missing</th></tr></thead><tbody>{enriched.map((r:any,i:number)=><tr key={i}><td>{r.lane.dc.code}</td><td>{r.lane.mode.code}</td><td>{r.lane.laneIdentifier??r.lane.destinationCountry+'-'+r.lane.destinationRegion}</td><td>{r.position}</td><td>{r.carrier.name}</td><td><span className={r.commercialStatus==='CONTRACTED_ACTIVE'?'badge ok':'badge warn'}>{r.commercialStatus}</span></td><td>€{r.base.toFixed(2)}</td><td>€{r.fuel.toFixed(2)}</td><td>€{r.accessorials.toFixed(2)}</td><td>€{r.total.toFixed(2)}</td><td>{Number.isFinite(cheapest.get(r.lane.id)??Infinity)?'€'+(r.total-(cheapest.get(r.lane.id)??0)).toFixed(2):'—'}</td><td>{r.breakEven??'—'}</td><td>{r.missing.join('; ')||'—'}</td></tr>)}</tbody></table></div>
  </AppShell>;
}
