import { AppShell } from '@/components/AppShell';
import { AuthGate } from '@/components/AuthGate';
import { PageHeader } from '@/components/Page';
import { prisma } from '@/lib/prisma';
import { tenantConfig } from '@/lib/tenant';

export default async function Page(){
  const s=await AuthGate(); const [dcs,modes,cfg]=await Promise.all([prisma.distributionCentre.findMany({where:{tenantId:s.tenantId},orderBy:{code:'asc'}}),prisma.transportMode.findMany({where:{tenantId:s.tenantId},orderBy:{code:'asc'}}),tenantConfig(s.tenantId)]);
  return <AppShell><PageHeader eyebrow="Tenant configuration" title="Settings" description="Control costing policy, resilience thresholds and governed master configuration for this tenant."/>
    <div className="summaryStrip"><div className="summaryCell"><div className="summaryLabel">Distribution centres</div><div className="summaryValue">{dcs.length}</div><div className="summaryNote">Configured operating origins</div></div><div className="summaryCell"><div className="summaryLabel">Transport modes</div><div className="summaryValue">{modes.length}</div><div className="summaryNote">Available costing structures</div></div><div className="summaryCell"><div className="summaryLabel">Min carrier coverage</div><div className="summaryValue">{cfg.minContractedCarriers}</div><div className="summaryNote">Required contracted alternatives</div></div><div className="summaryCell"><div className="summaryLabel">Expiry horizon</div><div className="summaryValue">{cfg.defaultExpiryHorizonDays}d</div><div className="summaryNote">Default commercial review window</div></div></div>
    <div className="card"><h2>Costing & coverage rules</h2><form action="/api/config" method="post" className="formgrid"><input type="hidden" name="action" value="config"/><div className="field"><label>Pallet rounding</label><select name="palletRounding" defaultValue={cfg.palletRounding}><option>UP</option><option>NEAREST</option></select></div><div className="field"><label>Above 36 pallets</label><select name="above36Policy" defaultValue={cfg.above36Policy}><option>FTL</option><option>SPLIT</option><option>ERROR</option></select></div><div className="field"><label>Max pallets per FTL</label><input type="number" name="maxPalletsPerFtl" defaultValue={cfg.maxPalletsPerFtl}/></div><div className="field"><label>Min active contracted carriers</label><input type="number" name="minContractedCarriers" defaultValue={cfg.minContractedCarriers}/></div><div className="field"><label>Default expiry horizon days</label><input type="number" name="defaultExpiryHorizonDays" defaultValue={cfg.defaultExpiryHorizonDays}/></div><div className="field"><label><input type="checkbox" name="requireFuelForCosting" defaultChecked={cfg.requireFuelForCosting}/> Treat missing fuel as a costing exception</label></div><div style={{alignSelf:'end'}}><button className="btn primary">Save versioned settings</button></div></form></div>
    <div className="section two"><div className="card"><h2>Add Distribution Centre</h2><form action="/api/config" method="post" className="stack"><input type="hidden" name="action" value="dc"/><div className="field"><label>Code</label><input name="code" required/></div><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Country code</label><input name="countryCode" maxLength={2} required/></div><div className="field"><label>Aliases</label><input name="aliases" placeholder="CZDC, CZ-DC"/></div><button className="btn primary">Add DC</button></form></div><div className="card"><h2>Add Transport Mode</h2><form action="/api/config" method="post" className="stack"><input type="hidden" name="action" value="mode"/><div className="field"><label>Code</label><input name="code" required/></div><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label><input type="checkbox" name="palletBand"/> Uses 1–36 pallet bands</label></div><button className="btn primary">Add mode</button></form></div></div>
    <div className="section two"><div className="card"><h2>Configured DCs</h2><div className="tableWrap"><table className="table"><thead><tr><th>Code</th><th>Name</th><th>Country</th><th>Aliases</th></tr></thead><tbody>{dcs.map(d=><tr key={d.id}><td>{d.code}</td><td>{d.name}</td><td>{d.countryCode}</td><td>{d.aliases.join(', ')}</td></tr>)}</tbody></table></div></div><div className="card"><h2>Configured modes</h2><div className="tableWrap"><table className="table"><thead><tr><th>Code</th><th>Name</th><th>Pallet bands</th></tr></thead><tbody>{modes.map(m=><tr key={m.id}><td>{m.code}</td><td>{m.name}</td><td>{m.palletBand?'Yes':'No'}</td></tr>)}</tbody></table></div></div></div>
  </AppShell>;
}
